# Generated by Django 5.1.3 on 2024-11-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_first_user_room_second_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
