# Generated by Django 5.1.3 on 2024-11-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_chatuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='creaed_at',
            new_name='created_at',
        ),
    ]
